### ISSUE TITLE
Get commitments from 3 judges

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/EndOfYearCelebrationAndAppContest2018#11]
- [x] Michael Faas from Aspen Entrepreneurs board 
- [x] Stephen Shapiro from School Blocks

Genevieve - can't
Dave Mayor - can't

**Comment by jcerise** [comment]
Do we still need a third judge?

**Comment by justinlewis** [comment]
@jcerise - Ya. I was thinking Mike Jahn but let me know if you have suggestions.
