### ISSUE TITLE
Purchase prizes

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/EndOfYearCelebrationAndAppContest2018#12]
- [x] Ski passes
- [x] Hot spring passes (10)
- [x] Coffee (3 one pound packages)
- [x] Rafting trip through Glenwood Adventure Company (value = $400)

**Comment by jcerise** [comment]
Do you still need help with this (judging by the unchecked boxes, I think yes)? What can I help purchase? Do we have funds for these purchases?

**Comment by justinlewis** [comment]
I'll be buying everything today. StartUp Colorado will reimburse me. Thanks for offering! I'll let you know if I can't get to all the things but I'm guessing it will be easier for reimbursement if it all comes from the same person.
