### ISSUE TITLE
Get supplies

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/EndOfYearCelebrationAndAppContest2018#3]
Pitch night (Friday) materials 
- [x] sticky notes
- [x] 8.5 x 11 paper for idea signs
- [ ] markers
- [x] disposable plates + utensils + cups
- [ ] signup sheet
- [x] Napkins
- [x] Tape
- [ ] Trash bin
- [ ] Folding table  

NOTE: I am unsure what the condition of the new space will be so we may need to bring in some things but I'm not sure what those might be at this point.

**Comment by jcerise** [comment]
Chairs? Tables? Projector?

**Comment by justinlewis** [comment]
We have everything we need for saturday including a little home projector. Maybe could use a couple chairs depending on how many people actually come. Right now it looks pretty small. 

For Friday we don't need chairs or a projector. I think it will be fine to do pitches all standing with simple paper and sticky notes. We need a table for food. I have one if need be but I'll check with Tyler to see if we can just bring one down stairs.
