### ISSUE TITLE
Determine App Contest rules and criteria

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/EndOfYearCelebrationAndAppContest2018#8]
Proposed judging criteria:
   -  (25%) Does the presentation show clarity of the idea?
   -  (25%) How likely is it that the idea solve an existing problem in the target community?
   -   ~~(25%) How likely is the idea to be adopted / used by the target community?~~
   -  (25%) How much value will this bring to the community?
   -  (25%) How likely is this idea able to be successfully implemented?

**Comment by jcerise** [comment]
"App Contest"...doesn't that kind of shoehorn things a bit? I thought we had discussed (and certainly, its the message I've been spreading) that this is not necessarily an app building contest. Weren't we trying to move away from that language for maximum comfort by people who attend?

Particularly since your language for criteria doesn't specifically call out apps.

**Comment by jcerise** [comment]
Also, should we have two judging tracks? One for ideas that were actually implemented in the time frame, and one for just concepts? Giving more points for actual implementation seems against the nature of the contest, but I feel like it should be taken into consideration. Maybe a sub category for anyone who actually implements?

**Comment by justinlewis** [comment]
We already changed it from Hackathon to App Challenge which was the attempt to make if more friendly.  It's ok to be working toward an app idea even if the app/prototype isn't built in this time frame. Whether a team produces an app or not is just part of their final presentation. I was hoping that the breakdown above would be applicable to any presentation regardless of if they have an app produced or not. A well refined idea and strategy can still enable people to rank high on the 1st three categories. 

I'm thinking we don't need two judging tracks so we can keep it super simple. If the judging criteria is focused on things like possibility of community impact and likelihood of "success". In that way producing an actual prototype might help rank higher IF the demo truly helps address the judging criteria or it could be a miss if all the time is spent building at the cost of not refining the product vision. 

... Regardless, the goal here is to create a fun and encouraging space to build things together as a community remembering that this is celebration + app challenge. So, here we should be thinking of how to judge in a way that best supports fun & friendly competition where support across teams is likely.  But the 1st way to set that precedence is to have a judging criteria that supports it. 

Make sense?

**Comment by justinlewis** [comment]
Suggestion was made to make the 3rd category more about value to a community rather than adoption because not every solution requires adoption.

**Comment by justinlewis** [comment]
Simplified description:  
 -  (25%) Clarity of the idea through presentation?
 -  (25%) Effectiveness at addressing the problem?
 -  (25%) Value to the community?
 -  (25%) Possibility of successful implementation?
